// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { CoreInstanceId } from "./CoreInstanceId";

export type ApiHandle = { instance_id: CoreInstanceId, api_version: ApiVersion, };
