// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider API Key 明文 newtype（SET-1，ADR-046）。
 *
 * wire 上是透明字符串；Debug 恒输出 `[REDACTED]`，禁止日志/错误路径
 * 泄漏明文。不实现 Display，避免被无意格式化进面向用户的输出。
 */
export type ApiKeySecret = string;
