// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorIdentity } from "./ActorIdentity";
import type { ApiVersion } from "./ApiVersion";
import type { AppCommand } from "./AppCommand";
import type { CommandId } from "./CommandId";
import type { CommandSource } from "./CommandSource";
import type { Timestamp } from "./Timestamp";

export type AppCommandEnvelope = { api_version: ApiVersion, command_id: CommandId, source: CommandSource, identity: ActorIdentity, expected_revision?: bigint | null, idempotency_key?: string | null, issued_at: Timestamp, command: AppCommand, };
