// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { ProviderId } from "./ProviderId";
import type { QuotaOverviewQuery } from "./QuotaOverviewQuery";
import type { RunId } from "./RunId";
import type { SessionId } from "./SessionId";
import type { WorkspaceId } from "./WorkspaceId";
import type { WorkspaceRelativePath } from "./WorkspaceRelativePath";

export type AppQuery = { "method": "workspace_list" } | { "method": "session_get", "params": { session_id: SessionId, timeline_after_sequence?: bigint | null, timeline_limit?: number | null, } } | { "method": "run_status", "params": { run_id: RunId, } } | { "method": "model_list", "params": { provider_id?: ProviderId | null, } } | { "method": "diff_list_files", "params": { workspace_id: WorkspaceId, } } | { "method": "diff_get", "params": { workspace_id: WorkspaceId, path: WorkspaceRelativePath, cursor?: string | null, } } | { "method": "artifact_read", "params": { artifact_id: ArtifactId, offset: bigint, limit: bigint, } } | { "method": "quota_overview", "params": { query: QuotaOverviewQuery, } } | { "method": "snapshot_fetch" } | { "method": "plugin_list" } | { "method": "mcp_list" } | { "method": "provider_auth_status", "params": { provider_id?: ProviderId | null, } } | { "method": "general_settings" } | { "method": "permissions_settings" } | { "method": "terminal_settings" };
