// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { AppResponse } from "./AppResponse";
import type { QueryId } from "./QueryId";
import type { Timestamp } from "./Timestamp";

export type AppResponseEnvelope = { api_version: ApiVersion, request_id: QueryId, responded_at: Timestamp, response: AppResponse, };
