// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";

export type ArtifactChunk = { request_id: string, artifact_id: ArtifactId, offset: bigint, data: Array<number>, eof: boolean, };
