// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider 认证变更状态机（SET-1，ADR-046）：终态与中间态全部脱敏，
 * `Succeeded` 只携带 method 与 masked_credential，绝无明文凭证。
 */
export type AuthChangeState = { "type": "pending" } | { "type": "succeeded", "data": { method: string, masked_credential: string, } } | { "type": "failed", "data": { error: string, } } | { "type": "cancelled" } | { "type": "expired" } | { "type": "removed" };
