// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientDiagnostic } from "./ClientDiagnostic";
import type { ClientDocumentContext } from "./ClientDocumentContext";

/**
 * 外部 Host 对一个 Core session 的全量、单调版本化上下文快照。
 *
 * 替换语义使断线重连可直接重放最新状态，不需要累积不可恢复的增量日志。
 */
export type ClientContextSnapshot = { revision: bigint, active_document?: string | null, open_documents?: Array<ClientDocumentContext>, diagnostics?: Array<ClientDiagnostic>, };
