// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppCommandEnvelope } from "./AppCommandEnvelope";
import type { AppQueryEnvelope } from "./AppQueryEnvelope";
import type { ArtifactReadRequest } from "./ArtifactReadRequest";
import type { GlobalSequence } from "./GlobalSequence";
import type { HandshakeRequest } from "./HandshakeRequest";
import type { ResumeRequest } from "./ResumeRequest";
import type { SubscribeRequest } from "./SubscribeRequest";

export type ClientFrame = { "type": "handshake", "data": HandshakeRequest } | { "type": "command", "data": AppCommandEnvelope } | { "type": "query", "data": AppQueryEnvelope } | { "type": "subscribe", "data": SubscribeRequest } | { "type": "unsubscribe", "data": { request_id: string, subscription_id: string, } } | { "type": "resume", "data": ResumeRequest } | { "type": "snapshot_request", "data": { request_id: string, } } | { "type": "ack", "data": { global_sequence: GlobalSequence, } } | { "type": "artifact_read", "data": ArtifactReadRequest } | { "type": "heartbeat", "data": { nonce: bigint, } } | { "type": "pong", "data": { nonce: bigint, } };
