// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 握手凭证只携带 opaque proof；协议日志必须单独执行 redaction。
 */
export type ClientAuthentication = { scheme: string, proof: string, };
