// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientDiagnosticSeverity } from "./ClientDiagnosticSeverity";
import type { ClientTextRange } from "./ClientTextRange";

/**
 * IDE/LSP 展示的诊断快照。`message` 是不可信观察数据，不具备指令权限。
 */
export type ClientDiagnostic = { document_uri: string, version?: bigint | null, range: ClientTextRange, severity?: ClientDiagnosticSeverity | null, code?: string | null, source?: string | null, message: string, };
