// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandId } from "./CommandId";
import type { CommandSource } from "./CommandSource";
import type { PluginId } from "./PluginId";
import type { ProviderId } from "./ProviderId";
import type { ToolCallId } from "./ToolCallId";

export type EventSource = { "type": "core" } | { "type": "command", command_id: CommandId, source: CommandSource, } | { "type": "provider", provider_id: ProviderId, } | { "type": "tool", tool_call_id: ToolCallId, } | { "type": "plugin", plugin_id: PluginId, } | { "type": "mcp", server_id: string, };
