// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuiClientId } from "./GuiClientId";
import type { RunId } from "./RunId";
import type { SessionId } from "./SessionId";
import type { WorkspaceId } from "./WorkspaceId";

export type EventStream = { "type": "global" } | { "type": "workspace", "id": WorkspaceId } | { "type": "session", "id": SessionId } | { "type": "run", "id": RunId } | { "type": "terminal", "id": string } | { "type": "gui_client", "id": GuiClientId };
