// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiHandle } from "./ApiHandle";
import type { ApiVersion } from "./ApiVersion";
import type { ConnectionId } from "./ConnectionId";
import type { GuiClientId } from "./GuiClientId";
import type { ProtocolError } from "./ProtocolError";
import type { ResumeDisposition } from "./ResumeDisposition";

export type HandshakeResponse = { "status": "accepted", request_id: string, selected_api_version: ApiVersion, handle: ApiHandle, client_id: GuiClientId, connection_id: ConnectionId, resume: ResumeDisposition, } | { "status": "rejected", request_id: string, error: ProtocolError, };
