// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { ClientAuthentication } from "./ClientAuthentication";
import type { GuiCapability } from "./GuiCapability";

export type HandshakeRequest = { request_id: string, client_name: string, client_version: string, supported_api_versions: Array<ApiVersion>, capabilities?: Array<GuiCapability>, authentication?: ClientAuthentication | null, };
