// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolErrorCode } from "./ProtocolErrorCode";

export type ProtocolError = { code: ProtocolErrorCode, message: string, retryable: boolean, };
