// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProtocolErrorCode = "incompatible_version" | "invalid_frame" | "authentication_failed" | "permission_denied" | "request_not_found" | "replay_unavailable" | "frame_too_large" | "busy" | "validation_failed" | "internal";
