// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolError } from "./ProtocolError";

export type ProtocolErrorEnvelope = { request_id?: string | null, error: ProtocolError, };
