// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider account selection policy (GUI 1.16).
 */
export type ProviderAccountSelectionMode = "manual" | "when_exhausted";
