// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical 配额单位。`Cost` 携带 ISO-4217 币种。
 */
export type QuotaUnit = { "kind": "count" } | { "kind": "token" } | { "kind": "cost", currency: string, };
