// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可信度优先级：exact > derived > scraped；默认最低信任 scraped。
 */
export type QuotaConfidence = "exact" | "derived" | "scraped";
