// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 稳定告警种类：与 quota-service `refresh::AlertKind` 1:1 镜像，serde
 * 形态冻结（snake_case）。消费端按 kind 派生可执行动作与文案，不解析
 * 自由文本 `message`；`Threshold` 的 advisory 语义由
 * [`QuotaAlertSeverity`] 区分（Warning = advisory 估算，Critical = 真实触限）。
 */
export type QuotaAlertKind = "threshold" | "recovered" | "stale" | "reauthorization_required" | "partial_failure";
