// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical 非负度量值。
 */
export type QuotaMeasure = { "kind": "exact", "value": bigint } | { "kind": "infinite" } | { "kind": "unknown" };
