// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * 窗口重置语义：绝对 / 相对 / 未知。
 */
export type QuotaReset = { "kind": "absolute", at: Timestamp, uncertain: boolean, } | { "kind": "relative", after_secs: bigint, observed_at: Timestamp, uncertain: boolean, } | { "kind": "unknown" };
