// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical 配额窗口。
 */
export type QuotaWindow = "overall" | "rolling5h" | "weekly" | "monthly";
