// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";
import type { QuotaAlertKind } from "./QuotaAlertKind";
import type { QuotaAlertSeverity } from "./QuotaAlertSeverity";
import type { QuotaSnapshotView } from "./QuotaSnapshotView";
import type { QuotaUnit } from "./QuotaUnit";
import type { QuotaWindow } from "./QuotaWindow";
import type { TenantId } from "./TenantId";

/**
 * 额度告警（安全 typed 视图，仅含脱敏字段）。
 *
 * `source` 是已脱敏的来源标签（adapter kind + 短来源名），不携带端点
 * query/fragment 或 secret/token/cookie 原文；`kind` 是稳定种类，动作由
 * 消费端派生。二者均为 `Option`：`kind`/`source` 是后加的持久化字段，
 * 旧事件 JSON 缺省时可解码为 `None`（重放兼容），新事件总是 `Some`。
 */
export type QuotaAlert = { tenant_id: TenantId, account_id: string, provider_id: ProviderId, model_id?: ModelId | null, window: QuotaWindow, unit: QuotaUnit, kind?: QuotaAlertKind | null, severity: QuotaAlertSeverity,
/**
 * 脱敏来源标签（adapter kind + 短来源名），永不包含 query/fragment
 * 或 secret/token/cookie 原文。
 */
source?: string | null, message: string, snapshot?: QuotaSnapshotView | null, credential_hint?: string | null, };
