// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalSequence } from "./GlobalSequence";

export type ResumeDisposition = { "type": "replay", from_sequence: GlobalSequence, through_sequence: GlobalSequence, } | { "type": "snapshot_required", earliest_available_sequence: GlobalSequence, } | { "type": "up_to_date", current_sequence: GlobalSequence, };
