// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalSequence } from "./GlobalSequence";

export type ResumeRequest = { request_id: string, last_global_sequence: GlobalSequence, };
