// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEventEnvelope } from "./AppEventEnvelope";
import type { AppResponseEnvelope } from "./AppResponseEnvelope";
import type { ArtifactChunk } from "./ArtifactChunk";
import type { CommandId } from "./CommandId";
import type { HandshakeResponse } from "./HandshakeResponse";
import type { ProtocolErrorEnvelope } from "./ProtocolErrorEnvelope";
import type { ResumeResponse } from "./ResumeResponse";
import type { Snapshot } from "./Snapshot";

export type ServerFrame = { "type": "handshake", "data": HandshakeResponse } | { "type": "command_accepted", "data": { request_id: string, command_id: CommandId, } } | { "type": "response", "data": AppResponseEnvelope } | { "type": "event", "data": AppEventEnvelope } | { "type": "snapshot", "data": Snapshot } | { "type": "resume", "data": ResumeResponse } | { "type": "artifact_chunk", "data": ArtifactChunk } | { "type": "error", "data": ProtocolErrorEnvelope } | { "type": "heartbeat", "data": { nonce: bigint, } } | { "type": "pong", "data": { nonce: bigint, } };
