// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotSectionKind = "workspaces" | "session_tree" | "active_runs" | "pending_tool_approvals" | "terminal_sessions" | "provider_status";
