// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { SnapshotSectionKind } from "./SnapshotSectionKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type SnapshotSection = { kind: SnapshotSectionKind, revision: bigint, 
/**
 * Snapshot 必须有界；大型内容改用 `artifact_id`。
 */
data?: JsonValue | null, artifact_id?: ArtifactId | null, };
