// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreInstanceId } from "./CoreInstanceId";
import type { GlobalSequence } from "./GlobalSequence";
import type { SnapshotSection } from "./SnapshotSection";
import type { Timestamp } from "./Timestamp";

export type Snapshot = { instance_id: CoreInstanceId, snapshot_sequence: GlobalSequence, generated_at: Timestamp, sections: Array<SnapshotSection>, };
