// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentInfo } from "./SubagentInfo";

/**
 * `subagent_list` query Data.
 */
export type SubagentListData = { agents: Array<SubagentInfo>, };
