// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live or completed subagent row.
 */
export type SubagentInfo = { agent_id: string, session_id: string, parent_run_id: string, title: string, provider_id: string, model_id: string, status: string, result?: string, };
