// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStream } from "./EventStream";

export type SubscribeRequest = { request_id: string, subscription_id: string, streams?: Array<EventStream>, };
