// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cost } from "./Cost";
import type { TaskUsageCostKind } from "./TaskUsageCostKind";

export type TaskUsageCost = { value: Cost, kind: TaskUsageCostKind, };
