// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageCurrencyTotal } from "./TaskUsageCurrencyTotal";
import type { TokenUsage } from "./TokenUsage";

export type TaskUsageTotals = { records: bigint, generation_calls: bigint, failed: bigint, cancelled: bigint, unfinished: bigint,
/**
 * 已知小计；必须与 unknown_token_calls 一起呈现。
 */
tokens: TokenUsage, unknown_token_calls: bigint, unknown_cost_calls: bigint, currencies: Array<TaskUsageCurrencyTotal>, output_images: bigint, planned_video_seconds: bigint, };
