// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageContext } from "./TaskUsageContext";
import type { TaskUsageCost } from "./TaskUsageCost";
import type { TaskUsageOperation } from "./TaskUsageOperation";
import type { TaskUsageSource } from "./TaskUsageSource";
import type { TaskUsageStatus } from "./TaskUsageStatus";
import type { TokenUsage } from "./TokenUsage";
import type { VideoTaskStatus } from "./VideoTaskStatus";

export type TaskUsageRecord = {
/**
 * Host 调用 ID；客户端报告使用独立命名空间。
 */
id: string, client: string, source: TaskUsageSource,
/**
 * 旧客户端没有显式关联时保留 None，查询仍可见。
 */
context: TaskUsageContext | null, operation: TaskUsageOperation, provider: string | null, model: string | null, started_at_ms: bigint, finished_at_ms: bigint | null, status: TaskUsageStatus,
/**
 * None 是未回传，不等于已确认的 0。
 */
tokens: TokenUsage | null, cost: TaskUsageCost | null, output_images: bigint | null,
/**
 * 固定生成参数的计划值，不能当实际扣费或实测媒体时长。
 */
planned_video_seconds: bigint | null, upstream_task_id: string | null, upstream_status: VideoTaskStatus | null,
/**
 * 状态查询 / 下载关联生成调用；不重复统计生成。
 */
related_call_id: string | null,
/**
 * 仅脱敏的分类码，不保存上游错误正文。
 */
error_code: string | null, };
