// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsage = { input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, cache_write_tokens: bigint, };
