// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { PluginId } from "./PluginId";

export type ActorIdentity = { "type": "local_user", actor_id: ActorId, display_name?: string | null, } | { "type": "authenticated_client", actor_id: ActorId, subject: string, } | { "type": "automation", name: string, } | { "type": "plugin", plugin_id: PluginId, } | { "type": "mcp_server", server_id: string, } | { "type": "system" };
