// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision";
import type { ClientContextSnapshot } from "./ClientContextSnapshot";
import type { EventId } from "./EventId";
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";
import type { RunId } from "./RunId";
import type { SessionId } from "./SessionId";
import type { ToolCallId } from "./ToolCallId";
import type { WorkspaceId } from "./WorkspaceId";
import type { WorkspaceRelativePath } from "./WorkspaceRelativePath";
import type { JsonValue } from "./serde_json/JsonValue";

export type AppCommand = { "method": "core_initialize" } | { "method": "workspace_add", "params": { root_path: string, } } | { "method": "workspace_trust", "params": { workspace_id: WorkspaceId, trusted: boolean, } } | { "method": "session_create", "params": { workspace_id: WorkspaceId, title?: string | null, } } | { "method": "session_open", "params": { session_id: SessionId, } } | { "method": "session_fork", "params": { session_id: SessionId, parent_event_id: EventId, } } | { "method": "session_compact", "params": { session_id: SessionId, } } | { "method": "session_client_context_replace", "params": { session_id: SessionId, snapshot: ClientContextSnapshot, } } | { "method": "run_start", "params": { session_id: SessionId, user_message: string, model?: ModelId | null,
/**
 * P17-5：可选 Agent Profile v2 名称。命中生产 `ResourceBundle.profiles_v2`
 * 时其不可变配置（prompt / canonical effort / tools / max_turns /
 * background / isolation / memory）成为该 run 的权威来源；未知 /
 * 跨 workspace / 引用不可用为结构化 fail-closed RunStart 错误。
 */
profile?: string | null, } } | { "method": "run_cancel", "params": { run_id: RunId, } } | { "method": "run_retry", "params": { run_id: RunId, } } | { "method": "run_tool", "params": { run_id: RunId, tool_name: string, input: JsonValue, } } | { "method": "auth_start", "params": { provider_id: ProviderId, flow: string, } } | { "method": "auth_remove", "params": { provider_id: ProviderId, } } | { "method": "tool_approve", "params": { run_id: RunId, tool_call_id: ToolCallId, decision: ApprovalDecision, } } | { "method": "git_stage", "params": { workspace_id: WorkspaceId, paths: Array<WorkspaceRelativePath>, } } | { "method": "terminal_create", "params": { workspace_id: WorkspaceId, working_directory?: WorkspaceRelativePath | null, } } | { "method": "terminal_write", "params": { terminal_session_id: string, data: string, } } | { "method": "terminal_resize", "params": { terminal_session_id: string, columns: number, rows: number, } };
