// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorIdentity } from "./ActorIdentity";
import type { ApiVersion } from "./ApiVersion";
import type { AppQuery } from "./AppQuery";
import type { CommandSource } from "./CommandSource";
import type { QueryId } from "./QueryId";
import type { Timestamp } from "./Timestamp";

export type AppQueryEnvelope = { api_version: ApiVersion, request_id: QueryId, source: CommandSource, identity: ActorIdentity, issued_at: Timestamp, query: AppQuery, };
