// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { CommandId } from "./CommandId";
import type { ErrorContext } from "./ErrorContext";
import type { JsonValue } from "./serde_json/JsonValue";

export type AppResponse = { "type": "accepted", "data": { command_id: CommandId, } } | { "type": "data", "data": JsonValue } | { "type": "artifact", "data": { artifact_id: ArtifactId, byte_length: bigint, media_type: string, } } | { "type": "error", "data": ErrorContext };
