// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host 观察到的文本位置；采用 LSP 的 zero-based line/character 语义，但不
 * 依赖任何 IDE/LSP crate，保持 Core canonical domain 中立。
 */
export type ClientTextPosition = { line: number, character: number, };
