// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientTextPosition } from "./ClientTextPosition";

export type ClientTextRange = { start: ClientTextPosition, end: ClientTextPosition, };
