// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientTextRange } from "./ClientTextRange";

/**
 * 单个打开文档的有限元数据。刻意不携带正文，只保留上下文定位和字节数提示，
 * 避免 IDE 通道变成绕过 Workspace/Policy 的文件读取入口。
 */
export type ClientDocumentContext = { uri: string, language_id: string, selection?: ClientTextRange | null, visible_range?: ClientTextRange | null, saved_version: bigint, text_bytes?: bigint | null, };
