// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId";
import type { GuiClientId } from "./GuiClientId";

export type CommandSource = { "type": "local_cli", terminal_session_id?: string | null, } | { "type": "local_gui", client_id: GuiClientId, } | { "type": "remote_gui", client_id: GuiClientId, connection_id: ConnectionId, } | { "type": "automation" } | { "type": "plugin" } | { "type": "mcp" };
