// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 以微单位保存费用，避免浮点数在持久化与跨语言传输时产生误差。
 */
export type Cost = { currency: string, amount_micros: bigint, };
