// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 跨 crate 稳定的错误大类；具体模块错误通过 `From` 转换到此分类。
 */
export type ErrorCategory = "provider" | "tool" | "internal" | "cancelled" | "rate_limit" | "timeout" | "authentication" | "authorization" | "invalid_request" | "not_found" | "conflict" | "resource_exhausted" | "unavailable" | "malformed_data";
