// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";
import type { QuotaUnit } from "./QuotaUnit";
import type { QuotaWindow } from "./QuotaWindow";
import type { TenantId } from "./TenantId";

/**
 * Quota 查询：tenant/account 必填，其余为可选过滤维度。
 */
export type QuotaOverviewQuery = { tenant_id: TenantId, account_id: string, provider_id?: ProviderId | null,
/**
 * 凭证元数据 ID（opaque，绝非凭证值）；视图输出时脱敏。
 */
credential_id?: string | null, model_id?: ModelId | null,
/**
 * 空表 = 默认所有支持的窗口。
 */
windows?: Array<QuotaWindow>, unit?: QuotaUnit | null, };
