// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical 适配器来源种类（脱敏枚举，不含任何凭证字段）。
 */
export type QuotaAdapterKind = "api_key_api" | "o_auth_api" | "web_scrape" | "local_ledger";
