// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaConfidence } from "./QuotaConfidence";
import type { QuotaProvenanceView } from "./QuotaProvenanceView";
import type { QuotaReset } from "./QuotaReset";
import type { QuotaScopeView } from "./QuotaScopeView";
import type { QuotaUnit } from "./QuotaUnit";
import type { QuotaValues } from "./QuotaValues";
import type { QuotaWindow } from "./QuotaWindow";

/**
 * 单窗口快照（脱敏后的 canonical 镜像）。
 */
export type QuotaSnapshotView = { scope: QuotaScopeView, window: QuotaWindow, unit: QuotaUnit, values: QuotaValues, reset: QuotaReset, confidence: QuotaConfidence, provenance: QuotaProvenanceView,
/**
 * 该快照是否来自过期缓存兜底（fresh 抓取失败）。
 */
served_stale: boolean, };
