// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";
import type { QuotaAlertSeverity } from "./QuotaAlertSeverity";
import type { QuotaSnapshotView } from "./QuotaSnapshotView";
import type { QuotaUnit } from "./QuotaUnit";
import type { QuotaWindow } from "./QuotaWindow";
import type { TenantId } from "./TenantId";

/**
 * 额度告警（安全 typed 视图，仅含脱敏字段）。
 */
export type QuotaAlert = { tenant_id: TenantId, account_id: string, provider_id: ProviderId, model_id?: ModelId | null, window: QuotaWindow, unit: QuotaUnit, severity: QuotaAlertSeverity, message: string, snapshot?: QuotaSnapshotView | null, credential_hint?: string | null, };
