// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaAdapterKind } from "./QuotaAdapterKind";

/**
 * typed 失败：适配器种类 + 错误码 + 脱敏详情。
 */
export type QuotaFailureView = { adapter_kind: QuotaAdapterKind,
/**
 * 错误短码（如 `forbidden`、`rate_limited`、`timeout`、`unsupported`）。
 */
error_code: string, detail: string, retry_after_ms?: bigint | null, };
