// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaAdapterKind } from "./QuotaAdapterKind";
import type { Timestamp } from "./Timestamp";

/**
 * 安全的来源元数据。`endpoint` 已去除 query/fragment，永不泄漏 token。
 */
export type QuotaProvenanceView = { adapter_kind: QuotaAdapterKind, source: string, endpoint?: string | null, fetched_at: Timestamp, observed_at?: Timestamp | null, stale: boolean, };
