// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";
import type { TenantId } from "./TenantId";

/**
 * 作用域视图：只暴露脱敏的 `credential_hint`，永不暴露凭证原文。
 */
export type QuotaScopeView = { tenant_id: TenantId, account_id: string, provider_id: ProviderId, model_id?: ModelId | null, credential_hint?: string | null, };
