// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunState = "created" | "preparing_context" | "waiting_for_provider" | "streaming_response" | "collecting_tool_calls" | "waiting_for_approval" | "executing_tools" | "appending_tool_results" | "completed" | "cancelled" | "failed" | "interrupted";
