// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-model spawn / subagent eligibility and permission names.
 */
export type SubagentModelRule = { provider_id: string, model_id: string, allow_spawn: boolean, allow_as_subagent: boolean, permissions: Array<string>, };
