// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageQuery } from "./TaskUsageQuery";
import type { TaskUsageTotals } from "./TaskUsageTotals";

export type TaskUsageGroup = { key: string, title: string, totals: TaskUsageTotals,
/**
 * 精确下钻条件；未关联维度没有可用的下钻条件。
 */
filter: TaskUsageQuery | null, };
