// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageOperation } from "./TaskUsageOperation";
import type { UsageTaskRef } from "./UsageTaskRef";

export type TaskUsageContext = { task: UsageTaskRef,
/**
 * 小说分部等分组；与二级任务正交，不增加任务层级。
 */
group: UsageTaskRef | null,
/**
 * 小说章节或视频分段。
 */
subtask: UsageTaskRef | null, operation: TaskUsageOperation,
/**
 * 明确补交的原调用 ID；不覆盖原调用或推测自动重试。
 */
retry_of: string | null, };
