// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageCursor } from "./TaskUsageCursor";
import type { TaskUsageGroup } from "./TaskUsageGroup";
import type { TaskUsageRecord } from "./TaskUsageRecord";
import type { TaskUsageTotals } from "./TaskUsageTotals";

export type TaskUsageReport = {
/**
 * 统计针对全部匹配记录，不受 limit / cursor 影响。
 */
totals: TaskUsageTotals, groups: Array<TaskUsageGroup>, records: Array<TaskUsageRecord>, next_cursor: TaskUsageCursor | null, };
