// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageContext } from "./TaskUsageContext";
import type { TaskUsageStatus } from "./TaskUsageStatus";

/**
 * 本地下载 / 导入 / 导出 / 编辑的客户端报告；不接受费用或 Token。
 */
export type TaskUsageOperationReport = { report_id: string, context: TaskUsageContext, status: TaskUsageStatus, started_at_ms: bigint, finished_at_ms: bigint, related_call_id: string | null, };
