// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskUsageCurrencyTotal = { currency: string, actual_micros: bigint, estimated_micros: bigint, actual_records: bigint, estimated_records: bigint, };
