// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 成员 presence 镜像（与 `teams::Presence` 1:1）。
 */
export type TeamPresence = "online" | "busy" | "idle" | "offline";
