// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamPlanStepStatus } from "./TeamPlanStepStatus";

/**
 * Plan 步骤快照镜像（与 `agent_domain::PlanStepSnapshot` 1:1）。
 */
export type TeamPlanStepSnapshot = { step_id: string, text: string, status: TeamPlanStepStatus, };
