// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CheckpointId } from "./CheckpointId";
import type { CommandId } from "./CommandId";
import type { MessageId } from "./MessageId";
import type { PlanId } from "./PlanId";
import type { PlanVersionId } from "./PlanVersionId";
import type { SessionId } from "./SessionId";
import type { TeamBoardTask } from "./TeamBoardTask";
import type { TeamMemberRole } from "./TeamMemberRole";
import type { TeamPlanCommentAnchor } from "./TeamPlanCommentAnchor";
import type { TeamPlanStepSnapshot } from "./TeamPlanStepSnapshot";
import type { TeamPresence } from "./TeamPresence";
import type { TeamRecipients } from "./TeamRecipients";
import type { TeamTaskState } from "./TeamTaskState";
import type { TenantId } from "./TenantId";

/**
 * Team 协作 canonical 事件镜像（与 `teams::TeamEvent` 1:1，18 变体）。
 */
export type TeamEvent = { "kind": "team_created", team_id: SessionId, tenant_id: TenantId, supervisor: AgentId, name: string, } | { "kind": "member_added", team_id: SessionId, agent_id: AgentId, role: TeamMemberRole, } | { "kind": "member_removed", team_id: SessionId, agent_id: AgentId, } | { "kind": "team_dissolved", team_id: SessionId, } | { "kind": "task_posted", team_id: SessionId, task: TeamBoardTask, } | { "kind": "task_claimed", team_id: SessionId, task_id: string, claimer: AgentId, } | { "kind": "task_released", team_id: SessionId, task_id: string, by: AgentId, } | { "kind": "task_advanced", team_id: SessionId, task_id: string, state: TeamTaskState, } | { "kind": "mailbox_posted", team_id: SessionId, message_id: MessageId, sender: AgentId, recipients: TeamRecipients, body: string, } | { "kind": "mailbox_delivered", team_id: SessionId, message_id: MessageId, recipient: AgentId, } | { "kind": "mailbox_read", team_id: SessionId, message_id: MessageId, by: AgentId, } | { "kind": "presence_changed", team_id: SessionId, agent_id: AgentId, presence: TeamPresence, } | { "kind": "peer_message_routed", team_id: SessionId, message_id: MessageId, fan_out_id: CommandId, sender: AgentId, recipients: TeamRecipients, body: string, } | { "kind": "fan_out_denied", team_id: SessionId, sender: AgentId, recipients: TeamRecipients, reason: string, } | { "kind": "plan_submitted", team_id: SessionId, plan_id: PlanId, version: PlanVersionId, title: string, steps: Array<TeamPlanStepSnapshot>, } | { "kind": "plan_approved", team_id: SessionId, plan_id: PlanId, version: PlanVersionId, checkpoint_id?: CheckpointId | null, } | { "kind": "plan_rejected", team_id: SessionId, plan_id: PlanId, version: PlanVersionId, reason: string, } | { "kind": "plan_commented", team_id: SessionId, plan_id: PlanId, version: PlanVersionId, anchor: TeamPlanCommentAnchor, body: string, };
