// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TeamTaskState } from "./TeamTaskState";

/**
 * 共享任务板条目镜像（与 `teams::BoardTask` 1:1）。
 */
export type TeamBoardTask = { task_id: string,
/**
 * 张贴者。
 */
poster: AgentId,
/**
 * 当前认领者；`None` 表示未认领。
 */
owner?: AgentId | null, description: string,
/**
 * 依赖的任务 id。
 */
depends_on: Array<string>, state: TeamTaskState, retry_count: number, max_retries: number, };
