// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plan 步骤状态镜像（与 `pawork_domain::PlanStepStatus` 1:1）。
 */
export type TeamPlanStepStatus = "pending" | "in_progress" | "completed" | "blocked";
