// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * mailbox 投递范围镜像（与 `teams::Recipients` 1:1）。
 */
export type TeamRecipients = { "kind": "direct", members: Array<AgentId>, } | { "kind": "broadcast" };
