// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 任务状态镜像（与 `orchestration::TaskState` 1:1，复用 P12 状态机）。
 */
export type TeamTaskState = "created" | "ready" | "assigned" | "running" | "blocked" | "completed" | "failed" | "cancelled";
