// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plan 行锚点镜像（与 `pawork_domain::PlanCommentAnchor` 1:1）。
 */
export type TeamPlanCommentAnchor = { step_id: string, line_offset?: number | null, file?: string | null, file_line?: number | null, };
