// @generated by schema-typegen; do not edit.

import type { ApiVersion } from "./ApiVersion";

export const API_VERSION: ApiVersion = { major: 1, minor: 0 };

export const SUPPORTED_API_VERSIONS: ReadonlyArray<ApiVersion> = [{ major: 1, minor: 0 }];
