// @generated by pawork-protocol-typegen; do not edit.

import type { ApiVersion } from "./ApiVersion";

export const API_VERSION: ApiVersion = { major: 1, minor: 5 };

export const SUPPORTED_API_VERSIONS: ReadonlyArray<ApiVersion> = [{ major: 1, minor: 0 }, { major: 1, minor: 1 }, { major: 1, minor: 2 }, { major: 1, minor: 3 }, { major: 1, minor: 4 }, { major: 1, minor: 5 }];
