// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remote video reference; the Host never downloads or decodes its contents.
 */
export type VideoContent = { url: string, media_type: string, };
