// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaWindow } from "./QuotaWindow";
import type { WindowReadView } from "./WindowReadView";

export type WindowReadEntry = { window: QuotaWindow, read: WindowReadView, };
