//! 协议 TypeScript declaration 生成与校验。
//!
//! 从 `CARGO_MANIFEST_DIR` 向上查找含 `[workspace]` 且含 `members` 的
//! `Cargo.toml` 作为仓库根；禁止硬编码 `join("../..")`。

use std::collections::BTreeMap;
use std::env;
use std::error::Error;
use std::ffi::OsStr;
use std::fmt::{Display, Formatter};
use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::TS;

use crate::headless::{HeadlessRequest, HeadlessResponse};
use crate::{
    AppCommandEnvelope, AppEventEnvelope, AppQueryEnvelope, AppResponseEnvelope, ClientFrame,
    ServerFrame, API_VERSION, SUPPORTED_API_VERSIONS,
};

type Result<T> = std::result::Result<T, TypegenError>;

#[derive(Debug)]
pub struct TypegenError(String);

impl Display for TypegenError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for TypegenError {}

impl From<String> for TypegenError {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl From<&str> for TypegenError {
    fn from(value: &str) -> Self {
        Self(value.to_string())
    }
}

impl From<std::io::Error> for TypegenError {
    fn from(error: std::io::Error) -> Self {
        Self(error.to_string())
    }
}

impl From<ts_rs::ExportError> for TypegenError {
    fn from(error: ts_rs::ExportError) -> Self {
        Self(error.to_string())
    }
}

/// 从 `start` 向上走，找到工作区根（含 `[workspace]` 且含 `members`）。
pub fn find_workspace_root(start: &Path) -> Result<PathBuf> {
    let mut current = start.to_path_buf();
    loop {
        let manifest = current.join("Cargo.toml");
        if manifest.is_file() {
            let text = fs::read_to_string(&manifest)?;
            if text.contains("[workspace]") && text.contains("members") {
                return Ok(current);
            }
        }
        if !current.pop() {
            return Err(TypegenError(format!(
                "no workspace Cargo.toml with [workspace] and members above {}",
                start.display()
            )));
        }
    }
}

fn workspace_root() -> Result<PathBuf> {
    find_workspace_root(Path::new(env!("CARGO_MANIFEST_DIR")))
}

/// 生成 `schemas/core-api`、`schemas/gui-protocol`、`schemas/headless-json`。
pub fn generate() -> Result<()> {
    run(false)
}

/// 校验检入的 `schemas/` 与当前类型导出一致。
pub fn check() -> Result<()> {
    run(true)
}

pub fn run(check_only: bool) -> Result<()> {
    let repository = workspace_root()?;
    let scratch = repository.join("target/schema-typegen");
    reset_scratch_directory(&scratch)?;

    let targets = [
        generate_core_api(&scratch.join("core-api"))?,
        generate_gui_protocol(&scratch.join("gui-protocol"))?,
        generate_headless_json(&scratch.join("headless-json"))?,
    ];

    for (schema_name, declarations) in targets {
        let destination = repository.join("schemas").join(schema_name);
        if check_only {
            check_declarations(&destination, &declarations)?;
        } else {
            write_declarations(&destination, &declarations)?;
        }
    }

    Ok(())
}

fn reset_scratch_directory(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    fs::create_dir_all(path)?;
    Ok(())
}

fn generate_core_api(output: &Path) -> Result<(&'static str, BTreeMap<String, String>)> {
    fs::create_dir_all(output)?;
    let config = ts_rs::Config::new().with_out_dir(output);
    AppCommandEnvelope::export_all(&config)?;
    AppQueryEnvelope::export_all(&config)?;
    AppResponseEnvelope::export_all(&config)?;
    AppEventEnvelope::export_all(&config)?;
    write_core_api_versions(output)?;
    Ok(("core-api", collect_declarations(output)?))
}

fn write_core_api_versions(output: &Path) -> Result<()> {
    let mut declaration =
        String::from("// @generated by pawork-protocol-typegen; do not edit.\n\n");
    declaration.push_str("import type { ApiVersion } from \"./ApiVersion\";\n\n");
    declaration.push_str(&format!(
        "export const API_VERSION: ApiVersion = {{ major: {}, minor: {} }};\n\n",
        API_VERSION.major, API_VERSION.minor
    ));
    declaration.push_str("export const SUPPORTED_API_VERSIONS: ReadonlyArray<ApiVersion> = [");
    let versions = SUPPORTED_API_VERSIONS
        .iter()
        .map(|version| format!("{{ major: {}, minor: {} }}", version.major, version.minor))
        .collect::<Vec<_>>()
        .join(", ");
    declaration.push_str(&versions);
    declaration.push_str("];\n");
    fs::write(output.join("versions.ts"), declaration)?;
    Ok(())
}

fn generate_gui_protocol(output: &Path) -> Result<(&'static str, BTreeMap<String, String>)> {
    fs::create_dir_all(output)?;
    let config = ts_rs::Config::new().with_out_dir(output);
    ClientFrame::export_all(&config)?;
    ServerFrame::export_all(&config)?;
    Ok(("gui-protocol", collect_declarations(output)?))
}

fn generate_headless_json(output: &Path) -> Result<(&'static str, BTreeMap<String, String>)> {
    fs::create_dir_all(output)?;
    let config = ts_rs::Config::new().with_out_dir(output);
    HeadlessRequest::export_all(&config)?;
    HeadlessResponse::export_all(&config)?;
    Ok(("headless-json", collect_declarations(output)?))
}

fn collect_declarations(source: &Path) -> Result<BTreeMap<String, String>> {
    let mut declarations = BTreeMap::new();
    collect_declarations_from(source, source, &mut declarations)?;

    let mut index = String::from("// @generated by pawork-protocol-typegen; do not edit.\n\n");
    for file_name in declarations.keys() {
        let declaration_path = file_name.trim_end_matches(".d.ts");
        if declaration_path == "versions" {
            index.push_str("export { API_VERSION, SUPPORTED_API_VERSIONS } from \"./versions\";\n");
            continue;
        }
        let type_name = Path::new(declaration_path)
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| format!("invalid generated declaration path: {file_name}"))?;
        index.push_str(&format!(
            "export type {{ {type_name} }} from \"./{declaration_path}\";\n"
        ));
    }
    declarations.insert("index.d.ts".into(), index);
    Ok(declarations)
}

fn collect_declarations_from(
    root: &Path,
    directory: &Path,
    declarations: &mut BTreeMap<String, String>,
) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_declarations_from(root, &path, declarations)?;
            continue;
        }
        if path.extension() != Some(OsStr::new("ts")) {
            continue;
        }

        let relative = path.strip_prefix(root).map_err(|error| error.to_string())?;
        let mut declaration_path = relative.to_path_buf();
        declaration_path.set_extension("d.ts");
        let declaration_name = declaration_path
            .to_str()
            .ok_or_else(|| format!("invalid generated file name: {}", path.display()))?
            .replace('\\', "/");
        declarations.insert(
            declaration_name,
            normalize_declaration(&fs::read_to_string(path)?),
        );
    }
    Ok(())
}

fn normalize_declaration(contents: &str) -> String {
    let trailing_newline = contents.ends_with('\n');
    let mut normalized = contents
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    if trailing_newline {
        normalized.push('\n');
    }
    normalized
}

fn write_declarations(destination: &Path, declarations: &BTreeMap<String, String>) -> Result<()> {
    fs::create_dir_all(destination)?;
    if destination.exists() {
        remove_generated_declarations(destination)?;
    }
    for (file_name, contents) in declarations {
        let path = destination.join(file_name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, contents)?;
    }
    Ok(())
}

fn remove_generated_declarations(directory: &Path) -> Result<()> {
    if !directory.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            remove_generated_declarations(&path)?;
        } else if path
            .file_name()
            .and_then(OsStr::to_str)
            .is_some_and(|name| name.ends_with(".d.ts"))
        {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

fn check_declarations(destination: &Path, expected: &BTreeMap<String, String>) -> Result<()> {
    let mut actual = BTreeMap::new();
    if destination.exists() {
        collect_existing_declarations(destination, destination, &mut actual)?;
    }

    if actual != *expected {
        let missing_or_changed = expected
            .iter()
            .filter(|(name, contents)| actual.get(*name) != Some(*contents))
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        let stale = actual
            .keys()
            .filter(|name| !expected.contains_key(*name))
            .map(String::as_str)
            .collect::<Vec<_>>();
        return Err(TypegenError(format!(
            "generated declarations are stale in {} (missing/changed: {:?}, stale: {:?}); run `cargo run -p pawork-protocol --features typegen --bin pawork-protocol-typegen`",
            destination.display(),
            missing_or_changed,
            stale
        )));
    }
    Ok(())
}

fn collect_existing_declarations(
    root: &Path,
    directory: &Path,
    declarations: &mut BTreeMap<String, String>,
) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_existing_declarations(root, &path, declarations)?;
            continue;
        }
        let Some(file_name) = path.file_name().and_then(OsStr::to_str) else {
            continue;
        };
        if !file_name.ends_with(".d.ts") {
            continue;
        }
        let relative = path
            .strip_prefix(root)
            .map_err(|error| error.to_string())?
            .to_str()
            .ok_or_else(|| format!("invalid declaration file name: {}", path.display()))?
            .replace('\\', "/");
        declarations.insert(relative, fs::read_to_string(path)?);
    }
    Ok(())
}
