// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { AppEvent } from "./AppEvent";
import type { CoreInstanceId } from "./CoreInstanceId";
import type { EventId } from "./EventId";
import type { EventSource } from "./EventSource";
import type { EventStream } from "./EventStream";
import type { GlobalSequence } from "./GlobalSequence";
import type { Timestamp } from "./Timestamp";

export type AppEventEnvelope = { api_version: ApiVersion, instance_id: CoreInstanceId, event_id: EventId, global_sequence: GlobalSequence, stream: EventStream, stream_sequence: bigint, timestamp: Timestamp, source: EventSource, payload: AppEvent, };
