// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * compat 导入选项。
 */
export type CompatImportOptions = {
/**
 * 只校验与解析，不落库（dry run 返回完整报告但不持久化）。
 */
dry_run: boolean, };
