// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatSource } from "./CompatSource";

/**
 * 导入历史条目（协议面）。
 */
export type CompatHistoryEntry = { session_id: string, source: CompatSource, original_id: string | null, imported_events: number, imported_at_unix_ms: bigint, };
