// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 生效默认模型配对（Host 顶层 `default` 对象；缺 provider/model 时为 JSON `null`）。
 */
export type DefaultModelPair = { provider_id: string, model_id: string, };
