// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { AppCommandEnvelope } from "./AppCommandEnvelope";
import type { AppQueryEnvelope } from "./AppQueryEnvelope";
import type { CompatImportOptions } from "./CompatImportOptions";
import type { CompatSource } from "./CompatSource";
import type { SdkCapability } from "./SdkCapability";

/**
 * 客户端 → Host 请求帧。
 */
export type HeadlessRequest = { "type": "hello", client_name: string, client_version: string, supported_api_versions: Array<ApiVersion>, capabilities: Array<SdkCapability>, } | { "type": "command", envelope: AppCommandEnvelope, } | { "type": "query", envelope: AppQueryEnvelope, } | { "type": "compat_import", request_id: string, source: CompatSource, content: string, options?: CompatImportOptions | null, } | { "type": "compat_history", request_id: string, limit?: number | null, cursor?: string | null, };
