// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiVersion } from "./ApiVersion";
import type { AppEventEnvelope } from "./AppEventEnvelope";
import type { AppResponseEnvelope } from "./AppResponseEnvelope";
import type { CompatHistoryEntry } from "./CompatHistoryEntry";
import type { CompatImportReport } from "./CompatImportReport";
import type { ProtocolErrorKind } from "./ProtocolErrorKind";
import type { SdkCapability } from "./SdkCapability";

/**
 * Host → 客户端响应帧。
 */
export type HeadlessResponse = { "type": "hello_ack", instance_id: string, negotiated: ApiVersion, granted: Array<SdkCapability>, } | { "type": "response", envelope: AppResponseEnvelope, } | { "type": "event", envelope: AppEventEnvelope, } | { "type": "compat_import_result", request_id: string, report: CompatImportReport, } | { "type": "compat_history_result", request_id: string, entries: Array<CompatHistoryEntry>, cursor?: string | null, } | { "type": "error", request_id?: string | null, kind: ProtocolErrorKind, message: string, };
