// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 显式协议错误类别。unknown / unsupported 都有独立类别，客户端可按类别
 * 决定降级路径（能力协商、版本升级或跳过）。
 */
export type ProtocolErrorKind = "unknown_request_type" | "unsupported_capability" | "incompatible_api_version" | "not_handshaked" | "malformed_frame" | "too_large" | "compat_rejected" | "backpressure" | "internal";
