// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaScopeView } from "./QuotaScopeView";
import type { Timestamp } from "./Timestamp";
import type { WindowReadEntry } from "./WindowReadEntry";

/**
 * Quota 总览视图：每个窗口一项，附生成时刻与是否命中缓存。
 */
export type QuotaOverviewView = { scope: QuotaScopeView, windows: Array<WindowReadEntry>, generated_at: Timestamp,
/**
 * 是否来自 quota-service 缓存；按需远端读取与无缓存视图均为 false。
 */
from_cache: boolean, };
