// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 协议对外可协商的能力（与 GUI Connection Protocol 的 capabilities 正交）。
 */
export type SdkCapability = "sessions" | "runs" | "streaming" | "compat_import" | "compat_history";
