// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentModelRule } from "./SubagentModelRule";

/**
 * Global subagent settings (query Data / `SetSubagentSettings` params).
 */
export type SubagentSettingsData = { enabled: boolean, max_concurrent: number, models: Array<SubagentModelRule>, };
