// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsageCursor } from "./TaskUsageCursor";
import type { TaskUsageGroupBy } from "./TaskUsageGroupBy";
import type { TaskUsageOperation } from "./TaskUsageOperation";
import type { TaskUsageStatus } from "./TaskUsageStatus";

export type TaskUsageQuery = { client: string | null, task_id: string | null, group_id: string | null, subtask_id: string | null, operation: TaskUsageOperation | null, provider: string | null, model: string | null, status: TaskUsageStatus | null,
/**
 * 时间半开区间 [start, end)。
 */
started_after_ms: bigint | null, started_before_ms: bigint | null, group_by: TaskUsageGroupBy, limit: number, cursor: TaskUsageCursor | null, };
