// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 成员角色镜像（与 `teams::MemberRole` 1:1）。
 */
export type TeamMemberRole = "supervisor" | "worker";
