// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 终端终态原因（ADR-045）：自然退出 / 经 terminal_close 终止 / 转发链路异常断流。
 */
export type TerminalExitReason = "exited" | "killed" | "failed";
