// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaFailureView } from "./QuotaFailureView";
import type { QuotaSnapshotView } from "./QuotaSnapshotView";

/**
 * 单个 (scope, window, unit) 读数结果。
 */
export type WindowReadView = { "status": "ok", snapshot: QuotaSnapshotView, failures?: Array<QuotaFailureView>, } | { "status": "failed", failures: Array<QuotaFailureView>, } | { "status": "no_data" };
