use std::{collections::BTreeMap, env, error::Error, ffi::OsStr, fs, path::Path};

use core_api::{AppCommandEnvelope, AppEventEnvelope, AppQueryEnvelope, AppResponseEnvelope};
use gui_protocol::{ClientFrame, ServerFrame};
use ts_rs::TS;

type Result<T> = std::result::Result<T, Box<dyn Error>>;

fn main() -> Result<()> {
    let check_only = match env::args().nth(1).as_deref() {
        None => false,
        Some("--check") => true,
        Some(argument) => return Err(format!("unknown argument: {argument}").into()),
    };

    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let scratch = repository.join("target/schema-typegen");
    reset_scratch_directory(&scratch)?;

    let targets = [
        generate_core_api(&scratch.join("core-api"))?,
        generate_gui_protocol(&scratch.join("gui-protocol"))?,
    ];

    for (schema_name, declarations) in targets {
        let destination = repository.join("schemas").join(schema_name);
        if check_only {
            check_declarations(&destination, &declarations)?;
        } else {
            write_declarations(&destination, &declarations)?;
        }
    }

    if check_only {
        println!("TypeScript declarations are up to date");
    } else {
        println!("TypeScript declarations generated under schemas/");
    }
    Ok(())
}

fn reset_scratch_directory(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    fs::create_dir_all(path)?;
    Ok(())
}

fn generate_core_api(output: &Path) -> Result<(&'static str, BTreeMap<String, String>)> {
    fs::create_dir_all(output)?;
    AppCommandEnvelope::export_all_to(output)?;
    AppQueryEnvelope::export_all_to(output)?;
    AppResponseEnvelope::export_all_to(output)?;
    AppEventEnvelope::export_all_to(output)?;
    write_core_api_versions(output)?;
    Ok(("core-api", collect_declarations(output)?))
}

/// 版本常量表（P13-10 schema 版本化）：ts-rs 不导出常量，由生成器直接落盘，
/// 使非 Rust 客户端拥有与 Rust 侧 `core_api::SUPPORTED_API_VERSIONS` 一致的协商基线。
fn write_core_api_versions(output: &Path) -> Result<()> {
    let mut declaration = String::from("// @generated by schema-typegen; do not edit.\n\n");
    declaration.push_str("import type { ApiVersion } from \"./ApiVersion\";\n\n");
    declaration.push_str(&format!(
        "export const API_VERSION: ApiVersion = {{ major: {}, minor: {} }};\n\n",
        core_api::API_VERSION.major,
        core_api::API_VERSION.minor
    ));
    declaration.push_str("export const SUPPORTED_API_VERSIONS: ReadonlyArray<ApiVersion> = [");
    let versions = core_api::SUPPORTED_API_VERSIONS
        .iter()
        .map(|version| format!("{{ major: {}, minor: {} }}", version.major, version.minor))
        .collect::<Vec<_>>()
        .join(", ");
    declaration.push_str(&versions);
    declaration.push_str("];\n");
    // 收集器会把 scratch 下的 *.ts 转成 *.d.ts，因此这里写 versions.ts，
    // 生成物是 schemas/core-api/versions.d.ts。
    fs::write(output.join("versions.ts"), declaration)?;
    Ok(())
}

fn generate_gui_protocol(output: &Path) -> Result<(&'static str, BTreeMap<String, String>)> {
    fs::create_dir_all(output)?;
    ClientFrame::export_all_to(output)?;
    ServerFrame::export_all_to(output)?;
    Ok(("gui-protocol", collect_declarations(output)?))
}

fn collect_declarations(source: &Path) -> Result<BTreeMap<String, String>> {
    let mut declarations = BTreeMap::new();
    collect_declarations_from(source, source, &mut declarations)?;

    let mut index = String::from("// @generated by schema-typegen; do not edit.\n\n");
    for file_name in declarations.keys() {
        let declaration_path = file_name.trim_end_matches(".d.ts");
        if declaration_path == "versions" {
            index.push_str("export { API_VERSION, SUPPORTED_API_VERSIONS } from \"./versions\";\n");
            continue;
        }
        let type_name = Path::new(declaration_path)
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| format!("invalid generated declaration path: {file_name}"))?;
        index.push_str(&format!(
            "export type {{ {type_name} }} from \"./{declaration_path}\";\n"
        ));
    }
    declarations.insert("index.d.ts".into(), index);
    Ok(declarations)
}

fn collect_declarations_from(
    root: &Path,
    directory: &Path,
    declarations: &mut BTreeMap<String, String>,
) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_declarations_from(root, &path, declarations)?;
            continue;
        }
        if path.extension() != Some(OsStr::new("ts")) {
            continue;
        }

        let relative = path.strip_prefix(root)?;
        let mut declaration_path = relative.to_path_buf();
        declaration_path.set_extension("d.ts");
        let declaration_name = declaration_path
            .to_str()
            .ok_or_else(|| format!("invalid generated file name: {}", path.display()))?
            .replace('\\', "/");
        declarations.insert(declaration_name, fs::read_to_string(path)?);
    }
    Ok(())
}

fn write_declarations(destination: &Path, declarations: &BTreeMap<String, String>) -> Result<()> {
    fs::create_dir_all(destination)?;
    remove_generated_declarations(destination)?;
    for (file_name, contents) in declarations {
        let path = destination.join(file_name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, contents)?;
    }
    Ok(())
}

fn remove_generated_declarations(directory: &Path) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            remove_generated_declarations(&path)?;
        } else if path
            .file_name()
            .and_then(OsStr::to_str)
            .is_some_and(|name| name.ends_with(".d.ts"))
        {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

fn check_declarations(destination: &Path, expected: &BTreeMap<String, String>) -> Result<()> {
    let mut actual = BTreeMap::new();
    if destination.exists() {
        collect_existing_declarations(destination, destination, &mut actual)?;
    }

    if actual != *expected {
        let missing_or_changed = expected
            .iter()
            .filter(|(name, contents)| actual.get(*name) != Some(*contents))
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        let stale = actual
            .keys()
            .filter(|name| !expected.contains_key(*name))
            .map(String::as_str)
            .collect::<Vec<_>>();
        return Err(format!(
            "generated declarations are stale in {} (missing/changed: {:?}, stale: {:?}); run `cargo run -p schema-typegen`",
            destination.display(),
            missing_or_changed,
            stale
        )
        .into());
    }
    Ok(())
}

fn collect_existing_declarations(
    root: &Path,
    directory: &Path,
    declarations: &mut BTreeMap<String, String>,
) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_existing_declarations(root, &path, declarations)?;
            continue;
        }
        let Some(file_name) = path.file_name().and_then(OsStr::to_str) else {
            continue;
        };
        if !file_name.ends_with(".d.ts") {
            continue;
        }
        let relative = path
            .strip_prefix(root)?
            .to_str()
            .ok_or_else(|| format!("invalid declaration file name: {}", path.display()))?
            .replace('\\', "/");
        declarations.insert(relative, fs::read_to_string(path)?);
    }
    Ok(())
}
